version: '3'

services:
  db:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB={{cookiecutter.db_name}}
      - POSTGRES_USER={{cookiecutter.db_user}}
      - POSTGRES_PASSWORD={{cookiecutter.db_pwd}}
    volumes:
      - db:/var/lib/postgresql
      - db_data:/var/lib/postgresql/data

volumes:
  db:
  db_data:
